# vim: ts=2:sw=2:sts=2:et:ft=yaml
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---

namespace: o0_o
name: inventory
version: 1.0.1
readme: README.md
authors:
  - oØ.o (@o0-o)
description: >
  POSIX-compatible Ansible plugins with raw fallback support for minimal systems.
license: GPL-3.0-or-later
tags:
  - collection
  - inventory
  - facts
repository: https://github.com/o0-o/ansible-collection-inventory
issues: https://github.com/o0-o/ansible-collection-inventory/issues
build_ignore:
  - .git
  - .github
  - .venv
  - .direnv
  - .wip
  - .pytest_cache
  - .mypy_cache
  - tests/output
  - __pycache__
